# .github/workflows/auto-publish.yml
name: CI
on:
  pull_request: {}
  push:
    branches: [main]
    
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
        # testing without github pages or figures dir on first pass
        # GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://github.com/w3c/patwg/issues/19
          TOOLCHAIN: bikeshed
          SOURCE: api.bs
          W3C_BUILD_OVERRIDE: |
            status: WD
            shortName: privacy-preserving-attribution
 