name: "Deploy to GitHub Pages"

on:
  push:
    branches: [ "main" ]
    paths: [ "Makefile", "api.bs", "images/**", ".github/workflows/deploy.yml", "impl/**" ]

jobs:
  build:
    name: "Build HTML"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: make
    - uses: actions/upload-pages-artifact@v3
      with:
        path: build

  publish:
    name: "Publish HTML"
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: $
    needs: build
    steps:
    - name: "Publish to GitHub Pages"
      uses: actions/deploy-pages@v4
