name: TypeScript Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflow/test-typescript.yml'
      - 'impl/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflow/test-typescript.yml'
      - 'impl/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'impl'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '>=22'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run pretty:check
      - run: npm run lint
